language: php
matrix:
  fast_finish: true
  include:
    - php: 7.4
      env: DB=mysql
      addons:
        mariadb: '10.2'
    - php: 7.4
      env: DB=pgsql
      sudo: true
      dist: trusty
      addons:
        postgresql: "9.5"
cache:
  directories:
    - $HOME/.composer/cache
before_install:
  - cd ..
  - git clone https://github.com/neos/neos-development-distribution.git -b dev-master
  - cd neos-development-distribution
  - composer require --no-update --no-interaction neos/content-repository-search dev-master
install:
  - COMPOSER_MEMORY_LIMIT=-1 composer install
  - cd ..
  - rm -rf neos-development-distribution/Packages/Application/Neos.ContentRepository.Search
  - mv content-repository-search neos-development-distribution/Packages/Application/Neos.ContentRepository.Search
  - cd neos-development-distribution

before_script:
  - phpenv config-rm xdebug.ini
  - echo 'date.timezone = "Antarctica/Troll"' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'opcache.fast_shutdown = 0' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'opcache.enable_cli = 0' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'zend.enable_gc = 0' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'report_zend_debug = 0' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - echo 'report_memleaks = 0' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - cp Configuration/Settings.yaml.example Configuration/Settings.yaml
  - Build/BuildEssentials/TravisCi/SetupDatabase.sh
  - cp Configuration/Settings.yaml Configuration/Testing/
  - ./flow flow:package:rescan
script:
  - bin/phpunit --colors -c Build/BuildEssentials/PhpUnit/UnitTests.xml Packages/Application/Neos.ContentRepository.Search/Tests/Unit
#  - bin/phpunit --colors --stop-on-failure -c Build/BuildEssentials/PhpUnit/FunctionalTests.xml Packages/Application/Neos.ContentRepository.Search/Tests/Functional
